### ISSUE TITLE
Add approvers filter in the ui

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/drive-ui#15]
3 options: 
1. You're blocked.
2. You are an approver.
3. Regular - receive a list of approvers from Kiddon. Add autocomplete to that.

**Comment by Shahar-Y** [comment]
@nogahaskal it it linked to the pr?

**Comment by Shahar-Y** [comment]
This version has a bug that needs fixing

**Comment by nettashviro** [comment]
finished #61

**Comment by Shahar-Y** [comment]
Closing. Done.Good job @nettashviro @nogahaskal
