### ISSUE TITLE
Change stepper in new external share

### ISSUE THREAD

**Issue by nettashviro** [meateam/drive-ui#58]
- [x] add step to the stepper: chose network and explain about each network- the user must understand the differences between the networks, change color of the pop-up background according to chosen network
- [x]  לשנות את הטאב יעד לטאב נמנעים ולקבל יוזרים לפי הרשת שבחרו - phonebook or kartffel+cts
- [x] approvals - change filter of approvals according to network
- [x] info - allow choosing ts for cts and differ by colors

**Comment by Shahar-Y** [comment]
Closing. Done.Good job @nettashviro
